# Generated by Django 2.2.7 on 2020-01-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_hubungan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hubungan',
        ),
    ]
